// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// ref: https://www.prisma.io/docs/orm/prisma-schema/overview/location
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
    seed:
      process.env["APP_ENV"] === "production"
        ? "tsx --env-file=.env dist/prisma/seeders/main.js"
        : "tsx --env-file=.env prisma/seeders/main.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
  },
});
