// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// ref: https://www.prisma.io/docs/orm/prisma-schema/overview/location
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
  },
});
